cust:
  server:
    servlet:
      context-path: /
    port: 80
  mysql:
    master:
      url: null
      username: null
      password: null
    slave: 
      enabled: false
      url: null
      username: null
      password: null
      