bear:
  demoEnabled: true
cust:
  server:
    servlet:
      context-path: /admin
    port: 8051
  redis: 
    enabled: true
    host: localhost
  mysql:
    master:
      url: localhost:3306/bear-auction
      username: root
      password: 123456
    slave:
      enabled: false
      url: null
      username: null
      password: null
shiro:
  anons: /auction/**, /foodano/*
  user:
    captchaEnabled: false